package com.trainingplus.model;

import com.google.appengine.tools.development.testing.LocalDatastoreServiceTestConfig;
import com.google.appengine.tools.development.testing.LocalServiceTestHelper;
import com.googlecode.objectify.Key;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyService;
import com.trainingplus.dao.ObjectifyDAO;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class ClubTest {

	private final LocalServiceTestHelper helper = new LocalServiceTestHelper(
			new LocalDatastoreServiceTestConfig());

	@Before
	public void setUp() {
		helper.setUp();
		new ObjectifyDAO();
	}

	@After
	public void tearDown() {
		helper.tearDown();
	}

	@Test
	public void CRUDClub() {
		Objectify ofy = ObjectifyService.begin();

		// Simple create
		Club barca = new Club("Barcelone");
		ofy.put(barca);
		assert barca.id != null; // id was autogenerated

		// Get it back
		Club fetched1 = ofy.get(new Key<Club>(Club.class, barca.id));
		Club fetched2 = ofy.get(Club.class, barca.id); // equivalent, more
		assertEquals("Objects seem to not be equals", fetched1, fetched2);

		// Change some data and write it
		barca.name = "psg";
		ofy.put(barca);
		assertNotSame("Name must be different", "Barcelone", ofy.get(Club.class, barca.id).name);
		
		Club real = new Club("Real");
		ofy.put(real);
		assertFalse("Objects must be different.", barca.equals(real));

		// Delete it
		ofy.delete(barca);
		ofy.delete(real);
	}

}
